version: '3'

services:
  rest_service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: